pull_request_rules:
        - name :
           conditions:
                - status-success-continuous-integration/travis-ci/pr                - "#approved-reviews-by>=2"
          actions:
             merge:
               method : merge
